/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 iPhone17Pro.glb -T 
Files: iPhone17Pro.glb [14.7MB] > C:\Users\taten\OneDrive\Desktop\Big ones\Apple 3d\frontend\public\models\iPhone17Pro-transformed.glb [334.61KB] (98%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/iPhone17Pro-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bolt001.geometry} material={materials.PaletteMaterial001} position={[0.083, -0.929, -0.051]} rotation={[-Math.PI, 0, 0]} scale={3.436} />
      <mesh geometry={nodes.Fresnel_Lens.geometry} material={materials.PaletteMaterial002} position={[-0.28, 0.785, -0.135]} rotation={[Math.PI / 2, 0, 0]} scale={[0.05, 0.008, 0.05]} />
      <mesh geometry={nodes['Light-Blocking_Plane'].geometry} material={nodes['Light-Blocking_Plane'].material} position={[0.005, 0.036, -0.065]} rotation={[Math.PI / 2, 0, 0]} scale={[0.424, 1, 0.885]} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Circle001.geometry} material={materials['LED DISPLAY ']} />
        <mesh geometry={nodes.Circle001_1.geometry} material={materials['Material.007']} />
      </group>
    </group>
  )
}

useGLTF.preload('/iPhone17Pro-transformed.glb')
