/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 iPadReal.glb -T 
Files: iPadReal.glb [1.45MB] > C:\Users\taten\OneDrive\Desktop\Big ones\Apple 3d\frontend\public\assets\iPad_Assets\iPadReal-transformed.glb [198.94KB] (86%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/iPadReal-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Text.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Face_sheet002.geometry} material={materials.PaletteMaterial002} />
      <mesh geometry={nodes.CameraandLight.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Bexel.geometry} material={materials.PaletteMaterial003} />
      <mesh geometry={nodes.SelfiCamera.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Screen.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Apple_logo001.geometry} material={materials.Apple_logo} position={[0, -0.006, 0]} />
    </group>
  )
}

useGLTF.preload('/iPadReal-transformed.glb')
