/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/WebIphone17.glb -o src/components/iPhone17ProScene.jsx --transform --names --keepmaterials 
Files: public/models/WebIphone17.glb [2.84MB] > C:\Users\taten\OneDrive\Desktop\Big ones\Apple 3d\frontend\src\components\WebIphone17-transformed.glb [814.4KB] (71%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/WebIphone17-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ttmRoLdJipiIOmf.geometry} material={materials.hUlRcbieVuIiOXG} scale={0.01} />
      <mesh geometry={nodes.DjsDkGiopeiEJZK.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <group scale={0.01}>
        <mesh geometry={nodes.buRWvyqhBBgcJFo_1.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.buRWvyqhBBgcJFo_2.geometry} material={materials.oZRkkORNzkufnGD} />
      </group>
      <mesh geometry={nodes.MrMmlCAsAxJpYqQ_0.geometry} material={materials.dxCVrUCvYhjVxqy} scale={0.01} />
      <mesh geometry={nodes.wqbHSzWaUxBCwxY_0.geometry} material={materials.MHFGNLrDQbTNima} scale={0.01} />
      <mesh geometry={nodes.QvGDcbDApaGssma.geometry} material={materials.kUhjpatHUvkBwfM} scale={0.01} />
      <mesh geometry={nodes.vFwJFNASGvEHWhs.geometry} material={materials.RJoymvEsaIItifI} scale={0.01} />
      <mesh geometry={nodes.evAxFwhaQUwXuua.geometry} material={materials.KSIxMqttXxxmOYl} scale={0.01} />
      <mesh geometry={nodes.USxQiqZgxHbRvqB.geometry} material={materials.mcPrzcBUcdqUybC} scale={0.01} />
      <mesh geometry={nodes.TvgBVmqNmSrFVfW.geometry} material={materials.pIhYLPqiSQOZTjn} scale={0.01} />
      <mesh geometry={nodes.pvdHknDTGDzVpwc.geometry} material={materials.xdyiJLYTYRfJffH} scale={0.01} />
      <mesh geometry={nodes.DjdhycfQYjKMDyn.geometry} material={materials.ujsvqBWRMnqdwPx} scale={0.01} />
      <mesh geometry={nodes.usFLmqcyrnltBUr.geometry} material={materials.sxNzrmuTqVeaXdg} scale={0.01} />
      <mesh geometry={nodes.xXDHkMplTIDAXLN.geometry} material={materials.pIJKfZsazmcpEiU} scale={0.01} />
      <mesh geometry={nodes.vELORlCJixqPHsZ.geometry} material={materials.zFdeDaGNRwzccye} scale={0.01} />
      <mesh geometry={nodes.EbQGKrWAqhBHiMv.geometry} material={materials.TBLSREBUyLMVtJa} scale={0.01} />
      <mesh geometry={nodes.EddVrWkqZTlvmci.geometry} material={materials.xNrofRCqOXXHVZt} scale={0.01} />
      <mesh geometry={nodes.KSWlaxBcnPDpFCs.geometry} material={materials.yQQySPTfbEJufve} scale={0.01} />
      <group scale={0.01}>
        <mesh geometry={nodes.wLfSXtbwRlBrwof_1.geometry} material={materials.eShKpuMNVJTRrgg} />
        <mesh geometry={nodes.wLfSXtbwRlBrwof_2.geometry} material={materials.PaletteMaterial003} />
      </group>
      <mesh geometry={nodes.WJwwVjsahIXbJpU.geometry} material={materials.yhcAXNGcJWCqtIS} scale={0.01} />
      <mesh geometry={nodes.YfrJNXgMvGOAfzz.geometry} material={materials.bCgzXjHOanGdTFV} scale={0.01} />
      <mesh geometry={nodes.DCLCbjzqejuvsqH.geometry} material={materials.vhaEJjZoqGtyLdo} position={[0.027, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.CdalkzDVnwgdEhS.geometry} material={materials.jlzuBkUzuJqgiAK} scale={0.01} />
      <mesh geometry={nodes.NtjcIgolNGgYlCg.geometry} material={materials.PpwUTnTFZJXxCoE} scale={0.01} />
      <mesh geometry={nodes.pXBNoLiaMwsDHRF.geometry} material={materials.yiDkEwDSyEhavuP} position={[0.021, 0.009, 0]} scale={0.01} />
      <mesh geometry={nodes.IkoiNqATMVoZFKD.geometry} material={materials.hiVunnLeAHkwGEo} position={[0.027, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.rqgRAGHOwnuBypi.geometry} material={materials.HGhEhpqSBZRnjHC} position={[0.027, 0, 0]} scale={0.01} />
      <group scale={0.01}>
        <mesh geometry={nodes.buRWvyqhBBgcJFo001_1.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.buRWvyqhBBgcJFo001_2.geometry} material={materials.eShKpuMNVJTRrgg} />
        <mesh geometry={nodes.buRWvyqhBBgcJFo001_3.geometry} material={materials.jpGaQNgTtEGkTfo} />
      </group>
    </group>
  )
}

useGLTF.preload('/WebIphone17-transformed.glb')
