/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/iPhone17Pro.glb -o src/components/iPhone17Pro.jsx --transform --names --keepmaterials 
Files: public/models/iPhone17Pro.glb [14.7MB] > C:\Users\taten\OneDrive\Desktop\Big ones\Apple 3d\frontend\src\components\iPhone17Pro-transformed.glb [346KB] (98%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/iPhone17Pro-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bolt001.geometry} material={materials['Material.006']} position={[0.083, -0.929, -0.051]} rotation={[-Math.PI, 0, 0]} scale={3.436} />
      <mesh geometry={nodes.Camera_Lenses.geometry} material={materials['Material.002']} position={[0.286, 0.527, -0.124]} rotation={[Math.PI / 2, 0, 0]} scale={[0.046, 0.022, 0.046]} />
      <mesh geometry={nodes.Camera001.geometry} material={materials['Inside Metal']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Charging_Port.geometry} material={materials['Material.006']} position={[0, -0.912, -0.051]} />
      <mesh geometry={nodes.Fresnel_Lens.geometry} material={materials['Material.004']} position={[-0.28, 0.785, -0.135]} rotation={[Math.PI / 2, 0, 0]} scale={[0.05, 0.008, 0.05]} />
      <mesh geometry={nodes['Light-Blocking_Plane'].geometry} material={nodes['Light-Blocking_Plane'].material} position={[0.005, 0.036, -0.065]} rotation={[Math.PI / 2, 0, 0]} scale={[0.424, 1, 0.885]} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Circle001.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Circle001_1.geometry} material={materials['Backside Neutral']} />
        <mesh geometry={nodes.Circle001_2.geometry} material={materials['Backside Apple Logo.001']} />
        <mesh geometry={nodes.Circle001_3.geometry} material={materials['LED DISPLAY ']} />
        <mesh geometry={nodes.Circle001_4.geometry} material={materials.Bezelmat} />
        <mesh geometry={nodes.Circle001_5.geometry} material={materials['Led Screen Glass']} />
        <mesh geometry={nodes.Circle001_6.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Circle001_7.geometry} material={materials.specialmetal} />
        <mesh geometry={nodes.Circle001_8.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/iPhone17Pro-transformed.glb')
